# Generated by Django 4.1.7 on 2023-07-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("PENDING", "Pending"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=100,
            ),
        ),
    ]
